zalopay:
  service:
    debug: true
    name: device

  data:
    es:
      useSSL: false
      url: http://10.50.1.20:9863/rsk/internal/device
      sizePerPage: 10
      clientId: 1
      secretKey: abc@123

  grpc:
    enable: false
    port: 9951
  dfp:
    alpha: 0.8
    threads: 8
    ttl: 86400

  redis:
    cluster: true
    nodeAddresses: 10.40.81.11:8000;10.40.81.11:8001;10.40.81.11:8002;10.40.81.11:8003;10.40.81.11:8004;10.40.81.11:8005
    delimiterAddress: ;
    scanInterval: 2000
    slaveConnectionMinimumIdleSize: 5
    slaveConnectionPoolSize: 5
    masterConnectionMinimumIdleSize: 5
    masterConnectionPoolSize: 5
    idleConnectionTimeout: 10000
    connectTimeout: 1000
    responseTimeout: 1000
    retryAttempts: 3
    retryInterval: 1000
    reconnectionTimeout: 3000
    failedAttempts: 3
    readMode: MASTER
    kryoCodec: true
    cachingTime: 2
    timeUnit: DAY
  kafka:
    app:
      brokers: 10.40.81.11:9630,10.40.81.11:9631,10.40.81.11:9632
      topic: log
      groupID: RMS_DFP_2011_3
      offsetReset: earliest
      enableAutoCommit: true
      sessionTimoutMs: 30000
      commitIntervalMs: 5000
      noComsumer: 1
    zpi:
      enable: false
      brokers:
      topic:
      groupID:
      offsetReset: earliest
      enableAutoCommit: true
      sessionTimoutMs: 30000
      commitIntervalMs: 5000
      noComsumer: 1
    promotion:
      enable: false
      brokers: 10.50.1.6:9092,10.50.1.7:9092,10.50.1.8:9092
      topic: device-promo
      acks: all
      retries: 3
      requestTimeoutMs: 15000
      retryBackoffMs: 1000

  datasource:
    url: "jdbc:mysql://10.50.1.3:3306/zpRMS_DFP?useSSL: false&useUnicode: yes&characterEncoding: UTF-8"
    sqlScriptEncoding: UTF-8                                                                                                              
    username: dbgtest                                                                                                                     
    password: abc@123                                                                                                                     
    driverClassName: com.mysql.jdbc.Driver                                                                                                
    maxActive: 50                                                                                                                         
    initSql: SET NAMES 'utf8mb4'                                                                                                          
    testWhileIdle: true                                                                                                                   
    validationQuery: SELECT
  entitymanager:
    batchSize: 5
    orderUpdates: true
    batchVersionedData: true

  proxy:
    host: 10.40.81.2
    port: 8088

spring:
  profiles:
    active: dev
  main:
    banner-mode: off

server:
  servlet:
    context-path: /device/
  port: 9950

logging:
  config: "file:./conf/log4j2.properties"
  level.*: info

  # Data service
  #zalopay.data.es.useSSL=false
  #zalopay.data.es.url=http://10.50.1.20:9863/rsk/internal/device
  #zalopay.data.es.sizePerPage=10
  #zalopay.data.es.clientId=1
  #zalopay.data.es.secretKey=abc@123
  #
  #z
  #
  #  # GRPC
  #zalopay.grpc.enable=false
  #zalopay.grpc.port=9951
  #
  #  # Proxy
  #zalopay.proxy.host=10.40.81.2
  #zalopay.proxy.port=8088

  # Logging
#  logging.config=file:./conf/log4j2.properties
#  logging.level.*=info
#
#  # Algorithm DFP
#  zalopay.dfp.alpha=0.8
#  zalopay.dfp.threads=8
#  zalopay.dfp.ttl=86400
#
#  # Redis
#  zalopay.redis.cluster=true
#  zalopay.redis.nodeAddresses=10.40.81.11:8000;10.40.81.11:8001;10.40.81.11:8002;10.40.81.11:8003;10.40.81.11:8004;10.40.81.11:8005
#  zalopay.redis.delimiterAddress=;
#  zalopay.redis.scanInterval=2000
#  zalopay.redis.slaveConnectionMinimumIdleSize=5
#  zalopay.redis.slaveConnectionPoolSize=5
#  zalopay.redis.masterConnectionMinimumIdleSize=5
#  zalopay.redis.masterConnectionPoolSize=5
#  zalopay.redis.idleConnectionTimeout=10000
#  zalopay.redis.connectTimeout=1000
#  zalopay.redis.responseTimeout=1000
#  zalopay.redis.retryAttempts=3
#  zalopay.redis.retryInterval=1000
#  zalopay.redis.reconnectionTimeout=3000
#  zalopay.redis.failedAttempts=3
#  zalopay.redis.readMode=MASTER
#  zalopay.redis.kryoCodec=true
#  zalopay.redis.cachingTime=2
#  zalopay.redis.timeUnit=DAY
#
#  # Kafka
#  zalopay.kafka.app.brokers=10.40.81.11:9630,10.40.81.11:9631,10.40.81.11:9632
#  zalopay.kafka.app.topic=log
#  zalopay.kafka.app.groupID=RMS_DFP_2011_3
#  zalopay.kafka.app.offsetReset=earliest
#  zalopay.kafka.app.enableAutoCommit=true
#  zalopay.kafka.app.sessionTimoutMs=30000
#  zalopay.kafka.app.commitIntervalMs=5000
#  zalopay.kafka.app.noComsumer=1
#
#  zalopay.kafka.zpi.enable=false
#  zalopay.kafka.zpi.brokers=
#  zalopay.kafka.zpi.topic=
#  zalopay.kafka.zpi.groupID=
#  zalopay.kafka.zpi.offsetReset=earliest
#  zalopay.kafka.zpi.enableAutoCommit=true
#  zalopay.kafka.zpi.sessionTimoutMs=30000
#  zalopay.kafka.zpi.commitIntervalMs=5000
#  zalopay.kafka.zpi.noComsumer=1
#
#  zalopay.kafka.promotion.enable=false
#  zalopay.kafka.promotion.brokers=10.50.1.6:9092,10.50.1.7:9092,10.50.1.8:9092
#  zalopay.kafka.promotion.topic=device-promo
#  zalopay.kafka.promotion.acks=all
#  zalopay.kafka.promotion.retries=3
#  zalopay.kafka.promotion.requestTimeoutMs=15000
#  zalopay.kafka.promotion.retryBackoffMs=1000
#
#  # MySQL
#  zalopay.datasource.url=jdbc:mysql://10.50.1.3:3306/zpRMS_DFP?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
#  zalopay.datasource.sqlScriptEncoding=UTF-8
#  zalopay.datasource.username=dbgtest
#  zalopay.datasource.password=abc@123
#  zalopay.datasource.driverClassName=com.mysql.jdbc.Driver
#  zalopay.datasource.maxActive=50
#  zalopay.datasource.initSql=SET NAMES 'utf8mb4'
#  zalopay.datasource.testWhileIdle=true
#  zalopay.datasource.validationQuery=SELECT
#  zalopay.entitymanager.batchSize=5
#  zalopay.entitymanager.orderUpdates=true
  zalopay.entitymanager.batchVersionedData=true

# UM
#um.baseUrl=https://dev.zalopay.com.vn/um/
#um.useProxy=1
#um.secondTimeout=20
#um.clientId=1
#um.clientKey=abc123
#um.updateLockUser=updatelockuser