zalopay:
  service:
    debug: true
    name: device

  data:
    es:
      useSSL: false
      url: http://10.50.1.20:9863/rsk/internal/device
      sizePerPage: 10
      clientId: 1
      secretKey: abc@123

  grpc:
    enable: false
    port: 9951
  dfp:
    alpha: 0.8
    threads: 8
    ttl: 86400

  redis:
    cluster: true
    nodeAddresses: 10.40.81.11:8000;10.40.81.11:8001;10.40.81.11:8002;10.40.81.11:8003;10.40.81.11:8004;10.40.81.11:8005
    delimiterAddress: ;
    scanInterval: 2000
    slaveConnectionMinimumIdleSize: 5
    slaveConnectionPoolSize: 5
    masterConnectionMinimumIdleSize: 5
    masterConnectionPoolSize: 5
    idleConnectionTimeout: 10000
    connectTimeout: 1000
    responseTimeout: 1000
    retryAttempts: 3
    retryInterval: 1000
    reconnectionTimeout: 3000
    failedAttempts: 3
    readMode: MASTER
    kryoCodec: true
    cachingTime: 2
    timeUnit: DAY
  kafka:
    app:
      brokers: 10.40.81.11:9630,10.40.81.11:9631,10.40.81.11:9632
      topic: log
      groupID: RMS_DFP_2011_3
      offsetReset: earliest
      enableAutoCommit: true
      sessionTimoutMs: 30000
      commitIntervalMs: 5000
      noComsumer: 1
    zpi:
      enable: false
      brokers:
      topic:
      groupID:
      offsetReset: earliest
      enableAutoCommit: true
      sessionTimoutMs: 30000
      commitIntervalMs: 5000
      noComsumer: 1
    promotion:
      enable: false
      brokers: 10.50.1.6:9092,10.50.1.7:9092,10.50.1.8:9092
      topic: device-promo
      acks: all
      retries: 3
      requestTimeoutMs: 15000
      retryBackoffMs: 1000

  datasource:
    url: "jdbc:mysql://10.50.1.3:3306/zpRMS_DFP?useSSL: false&useUnicode: yes&characterEncoding: UTF-8"
    sqlScriptEncoding: UTF-8                                                                                                              
    username: dbgtest                                                                                                                     
    password: abc@123                                                                                                                     
    driverClassName: com.mysql.jdbc.Driver                                                                                                
    maxActive: 50                                                                                                                         
    initSql: SET NAMES 'utf8mb4'                                                                                                          
    testWhileIdle: true                                                                                                                   
    validationQuery: SELECT
  entitymanager:
    batchSize: 5
    orderUpdates: true
    batchVersionedData: true

  proxy:
    host: 10.40.81.2
    port: 8088

spring:
  profiles:
    active: dev
  main:
    banner-mode: off

server:
  servlet:
    context-path: /device/
  port: 9950

logging:
  config: "file:./conf/log4j2.properties"
  level.*: info